name: medivault
description: MediVault - AI-Powered Personal Health Record & Medication Management App.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  fl_chart: ^0.66.0
  intl: ^0.19.0
  flutter_tts: ^3.8.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/medical_background.png
    - assets/images/stethoscope_bg.png
    - assets/images/stethoscope_light_bg.png
